
//   let b = 5;
//   a = 2+1;

// console.log("a ** b = " + (a ** b)); // 32console.log("Math.pow(a, b) = " + Math.pow(a, b)); // 32
// console.log("a++ = " + (a++)); // 3
// console.log(a); // 4
// assignments
// let c = 2;
// c -= 3; // c = c - 3
// console.log("c = " + c);
// let age = 25;
// let mode = "dark";
// let color;

// if (age>18) {
//     console.log("You are adult");
// }
// if (mode === "dark") {
//     color = "black";
// }
// if (mode === "light") {
//     color = "white";
// }
// console.log("color = " + color);
// if...else
// let num = 10;
// if (num % 2 === 0) {
//     console.log(num + " is even");
// } else {
//     console.log(num + " is odd");
// }
// for (let i = 1; i <= 5; i++) {
//     console.log("i = " + i);
// }
// let i =1 ;
// while (i<= 10){
//     console.log('ritesh');
//     i++
// }

// let i =1 ;
// while (i<= 10){
//     console.log(i);
//     i++
// }
// let i =1;
// do{
//     console.log(i);
//     i++
// }while(i<=10);

// for of loop
// let string = "ritesh rajput";
// let size = 0;
// for (let i of string) {
//     console.log("i=", i);
//     size++;
// }
// console.log("string size =",size );

// for in loop
// let student ={
//     name : "ritesh",
//     age : 19,
//     cgpa: 7.5,
//     ispass : true,
// };

// for (let key in student){
//     console.log("key =",key, "value =",student[key] );
// }
// for( i= 1;i<=100;i++){
//     if (i%2===0)
//     console.log(i)
// }
// let gamenum = 25,;
// let usernum = prompt("guess the game number");

// while (usernum != gamenum){
//      usernum = prompt(" you enterd wrong number .guess again:");
// }
//     console.log("congulation")

// let num =prompt("enter a number:");
// num = Number(num);

//      if (num > 0) {

//           console.log(num += "number is positive " );

//      }
//      else if (num < 0) {
//           console.log(num += "number is negative");
//      }
//      else {
//           console.log(num += "number is zero ");
//      }

// let age = prompt("enter your age:");
// age = Number(age);


// if(age>=18){
//      console.log(age+=  "congratul you are eligibility for vote");
// }
// else {45
//      console.log(age+="you are note eligibility for vote");
// }


// practice question 1
// let num = prompt('enter a number');

// if (num %7===0){
//      console.log(num,'is multiple of 7')
// }
// else {
//      console.log(nim," is not multiple of 7")
// }
//practice question 2

// let score = prompt("enter score 0-100")
// let grade;

// if (score >= 90 && score <= 100) {
//      grade = "A";
// }
// else if (score >= 70 && score >= 89) {
//      grade = "B";
// }
// else if (score>=60 && score<=79){
//      grade ="C"
// }
// else if (score>=50 && score<=59){
//      grade ="d"
// }
// else if (score>=0 && score<=49){
//      grade ="f";
// }
// console.log("according to your score , your grade was", grade)
// let string ="rakesh kumar";
// let size =0;
// for (let i of string){
//      console.log("i" ,i);
//      size++;
// }
// console.log ("string size",size);

// let student ={
//     name:  "ritesh",
//     age : 20 ,
//     cgpa :5.4,
//     ispass :true,

// };
  
//      for (let key in student){
//         console.log("key=",key, "value=",student[key]);
//      }\

// for (let num= 0; num<=100; num++){
//     {
//     if(num %2 === 0)
//     console.log(num)
//     }
// }
// let gamenum = 20;
//  let usernum =prompt( "GUSSE A NUMBER");

//  while(usernum !== gamenum){
//      usernum = prompt("you enterd wrong number . gusse again")
//  }
//  console.log( "happy")
let obj ={
    item : "pen ",
    price : 10,
};
let output =`the cost of ${obj.item} is ${obj.price} `

console.log("the cost of ",obj.item , "is ", obj.price,"rupes");

console.log(output);

console.log ("hi i am ritesh")

console.log("jindal");
console.log("jindal");
